#!/bin/sh

set -e

host="$1"

if [ ! "$host" ]; then
    echo "host required, eg. inithost 10.10.10.10"
    exit 1
fi
ip=$(echo "$host" | sed "s/:.*//")
port=$(echo "$host" | sed "s/.*://")

if [ "$port" = "$host" ]; then
    port=22
fi

pass1=""
pass2=""

echo -n "Password for admin user (leave blank for passwordless auth only) :"

stty -echo
read pass1
stty echo
echo ""

if [ "$pass1" != "" ]; then
    echo -n "Repeat password: "

    stty -echo
    read pass2
    stty echo
    echo ""

    if [ "$pass1" != "$pass2" ];then
        echo "ERROR: passwords didn't match"
        exit 1
    else
        echo "$pass1" > .adminpass
    fi
fi

# tar files
rm -rf build
mkdir build
cp tools/configure_ubuntu.sh build/server-init
cp -r tools/etc build
if [ -f keys/authorized_keys ]; then
    cp keys/authorized_keys build/etc
fi
if [ -f keys/*-admin-keys.zip ]; then
    reply=
    until [ "$reply" = "y" ] || [ "$reply" = "n" ]; do
        echo -n "Copy server admin keys to remote host? (Answer 'n' if using Agent Forwarding) [y/n] "
        read reply
    done
    if [ "$reply" = "y" ]; then
        cp keys/*-admin-keys.zip build
    fi
fi

if [ -e .adminpass ]; then
    cp .adminpass build
fi

cd build
tar -czvf prepare_ubuntu.tgz *
cd ..
mv build/prepare_ubuntu.tgz .
rm -rf build

#copy to remote server
echo ":: copying files to host"
scp -P $port prepare_ubuntu.tgz root@$ip:~
rm -rf prepare_ubuntu.tgz


